#!/usr/bin/env bash
# =============================================================================
# aid-active-index.sh — generated work/active.md index + shared post-boundary
# sync (P074 Step 6).
#
# WHY THIS EXISTS: `active.md` was agent-written prose read by five surfaces
# as "authoritative current state" — a single narrative that two concurrent
# streams corrupt with lost updates. This lib makes it a SMALL GENERATED
# INDEX of all active streams, regenerated by exactly four named writers at
# the lifecycle boundaries (init, done-advance, plan-close, plan-rollback)
# from state that already exists (plan-state, the active-runs map, the
# queue). Zero new state is introduced; plan-state stays the sole per-stream
# detail source.
#
# TWO SOURCEABLE FUNCTIONS — one definition, BOTH FSM layers source this file:
#
#   aid_active_index_refresh <state_root>
#     Renders <state_root>/.aid-o/work/active.md from
#     work/plan-state/*/plan-state.yaml (+ each plan's
#     plan-boundary-manifest.json for the EPIC set), work/active-runs.json,
#     and a one-line queue summary. One line per active (non-terminal) plan:
#     id, phase, worktree path, EPIC states. The first line is a header
#     naming the file as generated, so any agent reading it learns the
#     contract in-band. Atomic write (mktemp + mv in the file's own dir)
#     under a lib/aid-lock.sh sidecar flock (`active.md.lock`).
#     Best-effort contract: yq/jq absent, lock unobtainable, or an
#     unwritable target → WARN and leave the previous index in place, rc 1.
#     Missing plan-state dir / empty or absent map → a valid "no active
#     streams" index, rc 0.
#     LEGACY HAND-WRITTEN active.md: the first refresh overwrites it, but
#     preserves the old content ONCE as `active.md.pre-index` (detected by
#     the absence of the generated header on line 1; never re-preserved).
#
#   aid_active_boundary_sync <state_root> <epic_id> <boundary> [state_file]
#     The shared idempotent post-boundary helper both FSMs call. <boundary>
#     is one of: init | done-advance | plan-close | plan-rollback. It
#     performs the P074 Step 4 active-runs bookkeeping for that boundary
#     (init → upsert of [state_file]; done-advance/plan-close → removal of
#     <epic_id> when it names a real EPIC, "-" means plan-scoped/no entry),
#     then ALWAYS runs the Step 4 stale-entry sweep (`active-runs prune` —
#     the deferred prune wiring lands here), then refreshes the index.
#     The upsert/remove/prune FUNCTIONS live in aid-fsm.sh; when this helper
#     runs inside that process it calls them directly, and from any other
#     layer (aid-plan-fsm.sh's direct plan-close/plan-rollback) it invokes
#     the sibling `aid-fsm.sh active-runs prune` CLI with
#     AID_PROJECT_ROOT=<state_root> — identical cleanup either way, because
#     by plan-close/rollback time every one of the plan's EPIC runs is
#     terminal and prune sweeps it. ALWAYS returns 0: a render/bookkeeping
#     failure warns and never blocks the lifecycle operation that called it.
#
# Concurrency: two boundaries refreshing at once serialize on the flock;
# the render is a pure function of the source files, so last writer wins
# over identical state. Plan-state writes are atomic (tmp+mv), so the
# renderer never sees a torn file — a momentarily stale line self-corrects
# on the next boundary refresh.
#
# Pure bash + yq/jq over existing state files. Safe to source multiple times.
#
# **Last Updated:** 2026-08-06
# =============================================================================

if [[ -n "${_AID_ACTIVE_INDEX_SH_SOURCED:-}" ]]; then
  return 0 2>/dev/null || true
fi
_AID_ACTIVE_INDEX_SH_SOURCED=1

_AID_ACTIVE_INDEX_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1091
source "${_AID_ACTIVE_INDEX_LIB_DIR}/aid-lock.sh"

# The in-band contract line — MUST stay line 1 of every rendered index; the
# legacy-preservation check keys on it.
_AID_ACTIVE_INDEX_HEADER='<!-- generated by aid-active-index.sh — do not hand-edit; details live in .aid-o/work/plan-state/ -->'

aid_active_index_refresh() {
  local state_root="${1:-}"
  if [[ -z "$state_root" || ! -d "$state_root" ]]; then
    echo "WARNING: active-index: no usable state root ('${state_root}') — index not refreshed" >&2
    return 1
  fi
  if ! command -v yq >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
    echo "WARNING: active-index: yq/jq unavailable — previous active.md left in place" >&2
    return 1
  fi

  local work="${state_root}/.aid-o/work"
  local index="${work}/active.md"
  if ! mkdir -p "$work" 2>/dev/null; then
    echo "WARNING: active-index: cannot create ${work} — index not refreshed" >&2
    return 1
  fi
  if [[ -d "$index" ]]; then
    echo "WARNING: active-index: ${index} is a directory — cannot render the index (previous state left in place)" >&2
    return 1
  fi
  if ! aid_lock_acquire "${index}.lock" 5; then
    echo "WARNING: active-index: could not lock ${index}.lock — previous active.md left in place" >&2
    return 1
  fi
  local _ai_fd="$AID_LOCK_FD"

  # ── Active plans: one line per non-terminal plan-state ────────────────────
  local plans="" psf pid phase wt manifest epics n_plans=0
  for psf in "$work"/plan-state/*/plan-state.yaml; do
    [[ -f "$psf" ]] || continue
    pid="$(yq -r '.plan_id // ""' "$psf" 2>/dev/null || true)"
    phase="$(yq -r '.plan_state // ""' "$psf" 2>/dev/null || true)"
    [[ -n "$pid" ]] || continue
    case "$phase" in
      CLOSED|ABORTED|ROLLED_BACK) continue ;;
    esac
    # worktree_path is Step 7's optional field — "-" until a plan records one.
    wt="$(yq -r '.worktree_path // "-"' "$psf" 2>/dev/null || true)"
    [[ -n "$wt" && "$wt" != "null" ]] || wt="-"
    manifest="$(dirname "$psf")/plan-boundary-manifest.json"
    epics="-"
    if [[ -f "$manifest" ]]; then
      epics="$(jq -r '.plan_boundary_manifest as $m
        | "\($m.active_epics | length) active / \($m.total_epics // 0) total"
          + (if ($m.active_epics | length) > 0
             then " (" + ($m.active_epics | join(", ")) + ")" else "" end)' \
        "$manifest" 2>/dev/null || true)"
      [[ -n "$epics" ]] || epics="-"
    fi
    plans+="- ${pid} | phase=${phase:-?} | worktree=${wt} | epics: ${epics}"$'\n'
    n_plans=$((n_plans + 1))
  done
  [[ "$n_plans" -gt 0 ]] || plans="No active plan streams."$'\n'

  # ── Active EPIC runs: the Step 4 map, verbatim summary ────────────────────
  local runs="" map="${work}/active-runs.json"
  if [[ -e "$map" ]]; then
    runs="$(jq -r 'to_entries[]
      | "- \(.key) | state=\(.value.state // "?") | run=\(.value.run_id // "?") | branch=\(.value.branch // "?") | plan=\(.value.plan_id // "-")"' \
      "$map" 2>/dev/null || true)"
    [[ -n "$runs" ]] || runs="No active EPIC runs."
  else
    runs="No active EPIC runs."
  fi

  # ── Queue summary (one line; the file itself stays the detail source) ─────
  local queue="${state_root}/.aid-o/config/queue.yaml" queue_line qn
  if [[ -f "$queue" ]]; then
    qn="$(grep -c 'epic_id:' "$queue" 2>/dev/null || true)"
    [[ "$qn" =~ ^[0-9]+$ ]] || qn=0
    queue_line="${qn} queued entry(ies) — see .aid-o/config/queue.yaml"
  else
    queue_line="No queue file."
  fi

  # ── One-time preservation of a legacy hand-written active.md ──────────────
  if [[ -f "$index" && ! -e "${index}.pre-index" ]]; then
    local first_line=""
    IFS= read -r first_line < "$index" || true
    if [[ "$first_line" != "$_AID_ACTIVE_INDEX_HEADER" ]]; then
      if cp -p "$index" "${index}.pre-index" 2>/dev/null; then
        echo "active-index: preserved the previous hand-written active.md as active.md.pre-index (one-time)" >&2
      fi
    fi
  fi

  # ── Atomic write ──────────────────────────────────────────────────────────
  local tmp="" rc=0
  if ! tmp="$(mktemp "${index}.tmp.XXXXXX" 2>/dev/null)"; then
    aid_lock_release "$_ai_fd"
    echo "WARNING: active-index: cannot write next to ${index} — previous active.md left in place" >&2
    return 1
  fi
  {
    printf '%s\n' "$_AID_ACTIVE_INDEX_HEADER"
    printf '# Active Streams — generated index\n\n'
    printf 'Regenerated by the four lifecycle writers (init, done-advance, plan-close, plan-rollback).\n'
    printf 'READ for orientation only — hand edits are overwritten on the next refresh.\n'
    printf 'Per-stream detail lives in `.aid-o/work/plan-state/<plan_id>/`.\n\n'
    printf '## Active plans\n%s\n' "$plans"
    printf '## Active EPIC runs\n%s\n\n' "$runs"
    printf '## Queue\n%s\n\n' "$queue_line"
    printf '_Rendered: %s_\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } > "$tmp" 2>/dev/null || rc=1
  if [[ "$rc" -eq 0 ]]; then
    mv -- "$tmp" "$index" 2>/dev/null || rc=1
  fi
  if [[ "$rc" -ne 0 ]]; then
    rm -f -- "$tmp" 2>/dev/null || true
    echo "WARNING: active-index: could not replace ${index} — previous active.md left in place" >&2
  fi
  aid_lock_release "$_ai_fd"
  return "$rc"
}

aid_active_boundary_sync() {
  local state_root="${1:-}" epic_id="${2:-}" boundary="${3:-}" state_file="${4:-}"
  if [[ -z "$state_root" ]]; then
    echo "WARNING: active-index: boundary sync called with no state root — nothing done" >&2
    return 0
  fi

  # ── The boundary's own Step 4 bookkeeping (in-process functions when the
  #    caller is aid-fsm.sh; a plan-layer caller has none and relies on prune,
  #    which sweeps every terminal/gone run at close/rollback time). ──────────
  case "$boundary" in
    init)
      if [[ -n "$state_file" ]] && declare -F upsert_active_run >/dev/null 2>&1; then
        upsert_active_run "$state_file" || true
      fi
      ;;
    done-advance|plan-close)
      if [[ -n "$epic_id" && "$epic_id" != "-" ]] && declare -F remove_active_run >/dev/null 2>&1; then
        remove_active_run "$epic_id" "$boundary" || true
      fi
      ;;
    plan-rollback)
      : # no per-entry bookkeeping — the sweep below is the cleanup
      ;;
    *)
      echo "WARNING: active-index: unknown boundary '${boundary}' — sync limited to prune + refresh" >&2
      ;;
  esac

  # ── Step 4's deferred prune wiring: every boundary sweeps stale entries. ──
  if declare -F prune_active_runs >/dev/null 2>&1; then
    prune_active_runs || true
  else
    local _abs_fsm="${_AID_ACTIVE_INDEX_LIB_DIR}/../aid-fsm.sh"
    if [[ -f "$_abs_fsm" ]]; then
      AID_PROJECT_ROOT="$state_root" bash "$_abs_fsm" active-runs prune >/dev/null 2>&1 || true
    fi
  fi

  # ── The refresh — a failure warns, NEVER blocks the lifecycle operation. ──
  if ! aid_active_index_refresh "$state_root"; then
    echo "WARNING: active-index: refresh after ${boundary:-boundary} failed — the lifecycle operation itself is unaffected" >&2
  fi
  return 0
}
