#!/usr/bin/env bats
# test-active-index.bats — P074 Step 6: work/active.md as a generated index
# with four named writers.
#
# THE GROUNDED FAILURE MODE UNDER TEST: active.md was agent-written prose
# read by five surfaces as "authoritative current state" — a single
# narrative two concurrent streams corrupt with lost updates. Step 6 makes
# it a GENERATED index rendered from plan-state + the active-runs map +
# the queue by exactly four lifecycle writers (init, done-advance,
# plan-close, plan-rollback), all funneled through ONE shared helper
# (`aid_active_boundary_sync` in lib/aid-active-index.sh) that also lands
# Step 4's deferred prune wiring. The direct PLAN-layer close/rollback
# cases run the REAL `aid-plan-fsm.sh` commands (no aid-fsm.sh wrapper) to
# prove both layers share the one definition.
#
# FD-3 HYGIENE: every FSM invocation spawns children that must not hold
# bats' report fd — run them with `3>&-`. After any edit verify:
#   bats --tap test-active-index.bats | grep -cE '^(ok|not ok)'   # == 11

load test-helpers.bash

setup() {
  export AID_TEST_MODE=1 AID_QUIET=1 AID_CI=1
  AID_PLUGIN_PATH="$(cd "$BATS_TEST_DIRNAME/../../.." && pwd)"
  export AID_PLUGIN_PATH
  FSM="$AID_PLUGIN_PATH/scripts/aid-fsm.sh"
  PLAN_FSM="$AID_PLUGIN_PATH/scripts/aid-plan-fsm.sh"
  AI_LIB="$AID_PLUGIN_PATH/scripts/lib/aid-active-index.sh"
  export FSM PLAN_FSM AI_LIB
  TEST_TMPDIR="$(mktemp -d)"
  export TEST_TMPDIR
  unset AID_PROJECT_ROOT AID_PLAN_STATE_PROJECT_ROOT AID_PLAN_MANIFEST_PROJECT_ROOT
}

teardown() {
  cd /
  [[ -n "${TEST_TMPDIR:-}" && -d "$TEST_TMPDIR" ]] && rm -rf "$TEST_TMPDIR"
}

HEADER='<!-- generated by aid-active-index.sh — do not hand-edit; details live in .aid-o/work/plan-state/ -->'

# _mk_primary <dir> — committed primary checkout with the .aid-o skeleton
# cmd_init expects; .aid-o/ gitignored exactly like a real AID project.
# (Fixture style from test-active-runs-map.bats.)
_mk_primary() {
  local d="$1"
  mkdir -p "$d/.aid-o/plans" "$d/.aid-o/tasks" "$d/.aid-o/config" \
           "$d/.aid-o/work/evidence" "$d/.aid-o/work/runs"
  printf 'counter: 0\n' > "$d/.aid-o/config/counter.yaml"
  printf '.aid-o/\n' > "$d/.gitignore"
  printf 'seed\n' > "$d/README.md"
  (
    cd "$d"
    git init -q -b main 2>/dev/null || { git init -q; git checkout -q -b main 2>/dev/null || git branch -m main; }
    git config user.email aid-test@example.com
    git config user.name "AID Test"
    git add -A
    git commit -q -m "seed primary"
  )
}

# _seed_plan <root> <plan_id> <state> [worktree_path] — minimal plan-state.yaml
# (renderer input only; state legality is the plan FSM's own suites' business).
_seed_plan() {
  local d="$1" pid="$2" state="$3" wt="${4:-}"
  mkdir -p "$d/.aid-o/work/plan-state/$pid"
  {
    echo "plan_id: $pid"
    echo "plan_state: $state"
    echo "mode: plan_branch"
    if [[ -n "$wt" ]]; then echo "worktree_path: $wt"; fi
  } > "$d/.aid-o/work/plan-state/$pid/plan-state.yaml"
}

# _seed_stale_map <root> <epic> — a map entry claiming EXECUTE whose state
# file is GONE — exactly what the boundary sweep must remove.
_seed_stale_map() {
  local d="$1" epic="$2"
  mkdir -p "$d/.aid-o/work"
  jq -n --arg e "$epic" \
    '{($e): {state_file: (".aid-o/work/evidence/" + $e + "/R-X/fsm-state.yaml"),
             run_id: "R-X", state: "EXECUTE", branch: ("task/" + $e + "/main"),
             plan_id: null, governs_main: true, updated_at: "2026-01-01T00:00:00Z"}}' \
    > "$d/.aid-o/work/active-runs.json"
}

_refresh() {
  run bash -c "source '$AI_LIB' && aid_active_index_refresh '$1'" 3>&-
}

# ─── the renderer itself ─────────────────────────────────────────────────

@test "two active plans render as two lines (terminal plan excluded, header on line 1, worktree + EPIC states shown)" {
  local d="$TEST_TMPDIR/root"
  _seed_plan "$d" P901 OPEN
  _seed_plan "$d" P902 PLAN_GATES ".aid-worktrees/plan-P902"
  _seed_plan "$d" P903 CLOSED
  jq -n '{plan_boundary_manifest: {epics: ["E-902-1_2","E-902-2_2"],
          active_epics: ["E-902-1_2"], total_epics: 2}}' \
    > "$d/.aid-o/work/plan-state/P902/plan-boundary-manifest.json"
  _refresh "$d"
  [ "$status" -eq 0 ]
  local idx="$d/.aid-o/work/active.md"
  [ -f "$idx" ]
  [ "$(head -1 "$idx")" = "$HEADER" ]
  run grep -c '^- P90' "$idx"
  [ "$output" = "2" ]
  run grep '^- P902' "$idx"
  [[ "$output" == *"phase=PLAN_GATES"* ]]
  [[ "$output" == *"worktree=.aid-worktrees/plan-P902"* ]]
  [[ "$output" == *"1 active / 2 total (E-902-1_2)"* ]]
  ! grep -q '^- P903' "$idx"
}

@test "missing plan-state dir + no map + no queue renders a valid 'no active streams' index" {
  local d="$TEST_TMPDIR/root"
  mkdir -p "$d"
  _refresh "$d"
  [ "$status" -eq 0 ]
  local idx="$d/.aid-o/work/active.md"
  [ "$(head -1 "$idx")" = "$HEADER" ]
  grep -q 'No active plan streams\.' "$idx"
  grep -q 'No active EPIC runs\.' "$idx"
  grep -q 'No queue file\.' "$idx"
}

@test "legacy hand-written active.md is preserved ONCE as active.md.pre-index; a later hand edit is overwritten and NOT re-preserved" {
  local d="$TEST_TMPDIR/root"
  _seed_plan "$d" P901 OPEN
  printf 'MY HAND-WRITTEN NARRATIVE\n' > "$d/.aid-o/work/active.md"
  _refresh "$d"
  [ "$status" -eq 0 ]
  # first overwrite preserved the legacy content
  [ -f "$d/.aid-o/work/active.md.pre-index" ]
  grep -q 'MY HAND-WRITTEN NARRATIVE' "$d/.aid-o/work/active.md.pre-index"
  [ "$(head -1 "$d/.aid-o/work/active.md")" = "$HEADER" ]
  # a hand edit of the GENERATED file is overwritten on the next refresh —
  # and pre-index keeps the ORIGINAL, never the sneaky edit
  printf 'SNEAKY HAND EDIT\n' > "$d/.aid-o/work/active.md"
  _refresh "$d"
  [ "$status" -eq 0 ]
  ! grep -q 'SNEAKY' "$d/.aid-o/work/active.md"
  grep -q '^- P901' "$d/.aid-o/work/active.md"
  grep -q 'MY HAND-WRITTEN NARRATIVE' "$d/.aid-o/work/active.md.pre-index"
  ! grep -q 'SNEAKY' "$d/.aid-o/work/active.md.pre-index"
}

# ─── writer 1: init ──────────────────────────────────────────────────────

@test "writer 1 (aid-fsm.sh init) refreshes the index and its run appears in it" {
  _mk_primary "$TEST_TMPDIR/primary"
  run bash -c "cd '$TEST_TMPDIR/primary' \
    && '$FSM' init E-901-1_1 R-A 1 manual main HEAD '.aid-o/work/evidence/E-901-1_1/R-A/fsm-state.yaml'" 3>&-
  [ "$status" -eq 0 ]
  local idx="$TEST_TMPDIR/primary/.aid-o/work/active.md"
  [ -f "$idx" ]
  [ "$(head -1 "$idx")" = "$HEADER" ]
  run grep 'E-901-1_1' "$idx"
  [[ "$output" == *"state=READY"* ]]
  [[ "$output" == *"run=R-A"* ]]
}

# ─── writer 2: done-advance ──────────────────────────────────────────────

@test "writer 2 (done-advance review→release) refreshes the index — the released run drops off, the concurrent run stays" {
  _mk_primary "$TEST_TMPDIR/primary"
  run bash -c "cd '$TEST_TMPDIR/primary' \
    && '$FSM' init E-901-1_1 R-A 1 manual main HEAD '.aid-o/work/evidence/E-901-1_1/R-A/fsm-state.yaml' \
    && git checkout -q main \
    && '$FSM' init E-902-1_1 R-B 1 manual main HEAD '.aid-o/work/evidence/E-902-1_1/R-B/fsm-state.yaml'" 3>&-
  [ "$status" -eq 0 ]
  local sfA="$TEST_TMPDIR/primary/.aid-o/work/evidence/E-901-1_1/R-A/fsm-state.yaml"
  sed -i 's/^state: READY/state: DONE/' "$sfA"
  echo "done_phase: review" >> "$sfA"
  run bash -c "cd '$TEST_TMPDIR/primary' && '$FSM' done-advance review release \
    '.aid-o/work/evidence/E-901-1_1/R-A/fsm-state.yaml' \
    --force --reason 'PM-authorized test override to reach the boundary sync path'" 3>&-
  [ "$status" -eq 0 ]
  local idx="$TEST_TMPDIR/primary/.aid-o/work/active.md"
  [ "$(head -1 "$idx")" = "$HEADER" ]
  ! grep -q 'E-901-1_1' "$idx"
  grep -q 'E-902-1_1' "$idx"
}

# ─── writer 3: plan-close (both layers) ──────────────────────────────────

@test "writer 3 (aid-fsm.sh plan-close, EPIC layer) refreshes the index" {
  # Fixture shape from test-plan-close.bats: evidence_dir == project_root,
  # committed Head-fresh delivery report so the close-check passes.
  local d="$TEST_TMPDIR/primary"
  _mk_primary "$d"
  mkdir -p "$d/.aid-o/reports"
  touch "$d/curator-report.md" "$d/audit-report.md" "$d/simplifier-report.md"
  local head; head="$(git -C "$d" rev-parse HEAD)"
  printf -- '---\nHead: %s\n---\n# P046 Delivery Report\n' "$head" \
    > "$d/.aid-o/reports/P046-delivery.md"
  # the report is gitignored under .aid-o/ in this fixture, so Head stays fresh
  rm -f "$d/.aid-o/work/active.md"
  run bash -c "cd '$d' && '$FSM' plan-close E-046-2_3 '$d' '$d'" 3>&-
  [ "$status" -eq 0 ]
  [ -f "$d/ca-review-complete" ]
  [ -f "$d/.aid-o/work/active.md" ]
  [ "$(head -1 "$d/.aid-o/work/active.md")" = "$HEADER" ]
}

@test "writer 3 (DIRECT aid-plan-fsm.sh plan-close, PLAN layer) sweeps the stale run entry and refreshes the index" {
  local d="$TEST_TMPDIR/primary"
  _mk_primary "$d"
  # a real plan in ABORTED with its boundary manifest, closed by abort mode;
  # --force waives only the bookkeeping close-check (forceable by design)
  run bash -c "
    export AID_PLAN_STATE_PROJECT_ROOT='$d' AID_PLAN_MANIFEST_PROJECT_ROOT='$d'
    source '$AID_PLUGIN_PATH/scripts/lib/aid-plan-state.sh'
    source '$AID_PLUGIN_PATH/scripts/lib/aid-plan-manifest.sh'
    base=\$(git -C '$d' rev-parse main)
    git -C '$d' branch plan/P901 \"\$base\"
    plan_state_init P901 plan_branch plan/P901 main
    plan_manifest_init P901 plan/P901 main \"\$base\" \"\$base\" plan_branch
    yq -i '.plan_state = \"ABORTED\" | .terminal_reason = \"test abort\"' \
      '$d/.aid-o/work/plan-state/P901/plan-state.yaml'
    plan_manifest_update P901 '.plan_boundary_manifest.plan_state = \"ABORTED\" | .plan_boundary_manifest.terminal_reason = \"test abort\"'
  " 3>&-
  [ "$status" -eq 0 ]
  # stale entry: map claims EXECUTE, live state file is terminal DONE
  mkdir -p "$d/.aid-o/work/evidence/E-901-1_1/R-X"
  printf 'epic_id: E-901-1_1\nrun_id: R-X\nstate: DONE\nbranch: task/E-901-1_1/main\n' \
    > "$d/.aid-o/work/evidence/E-901-1_1/R-X/fsm-state.yaml"
  jq -n '{"E-901-1_1": {state_file: ".aid-o/work/evidence/E-901-1_1/R-X/fsm-state.yaml",
          run_id: "R-X", state: "EXECUTE", branch: "task/E-901-1_1/main",
          plan_id: "P901", governs_main: true, updated_at: "2026-01-01T00:00:00Z"}}' \
    > "$d/.aid-o/work/active-runs.json"
  run bash -c "'$PLAN_FSM' plan-close P901 --project-root '$d' \
    --force --force-reason 'test: exercise the direct plan-layer close boundary sync'" 3>&-
  [ "$status" -eq 0 ]
  [ -f "$d/.aid-o/work/plan-state/P901/plan-close-complete" ]
  # the boundary sweep removed the terminal run's entry (prune via the CLI
  # fallback — the plan layer has no in-process Step 4 functions)
  run jq -r 'keys | length' "$d/.aid-o/work/active-runs.json"
  [ "$output" = "0" ]
  # index rendered; the ABORTED plan is not an active stream
  local idx="$d/.aid-o/work/active.md"
  [ "$(head -1 "$idx")" = "$HEADER" ]
  grep -q 'No active plan streams\.' "$idx"
  grep -q 'No active EPIC runs\.' "$idx"
}

# ─── writer 4: plan-rollback (direct, PLAN layer) ────────────────────────

@test "writer 4 (DIRECT aid-plan-fsm.sh plan-rollback) sweeps the map and refreshes the index — the ROLLED_BACK plan drops off" {
  local d="$TEST_TMPDIR/primary"
  _mk_primary "$d"
  run bash -c "
    set -e
    export AID_PLAN_STATE_PROJECT_ROOT='$d' AID_PLAN_MANIFEST_PROJECT_ROOT='$d'
    source '$AID_PLUGIN_PATH/scripts/lib/aid-plan-state.sh'
    source '$AID_PLUGIN_PATH/scripts/lib/aid-plan-manifest.sh'
    source '$AID_PLUGIN_PATH/scripts/lib/aid-lifecycle.sh'
    printf '# P902\n\n**EPIC 1: the delivered one**\n' > '$d/.aid-o/plans/P902-lifecycle.md'
    aid_lifecycle_ensure_manifest P902 '$d' >/dev/null
    aid_lifecycle_set_plan_mode P902 plan_branch '$d' >/dev/null
    base=\$(git -C '$d' rev-parse main)
    git -C '$d' branch plan/P902 \"\$base\"
    git -C '$d' checkout -q plan/P902
    printf 'delivered\n' > '$d/epic-work.txt'
    git -C '$d' add epic-work.txt && git -C '$d' commit -q -m deliver
    cand=\$(git -C '$d' rev-parse plan/P902)
    git -C '$d' checkout -q main
    tb=\$(git -C '$d' rev-parse main)
    git -C '$d' merge -q --no-ff -m 'merge plan/P902' plan/P902
    mc=\$(git -C '$d' rev-parse main)
    git -C '$d' revert -m 1 --no-edit \"\$mc\" >/dev/null 2>&1
    rev=\$(git -C '$d' rev-parse main)
    plan_state_init P902 plan_branch plan/P902 main >/dev/null
    yq -i '.plan_state = \"PLAN_MERGING\"' '$d/.aid-o/work/plan-state/P902/plan-state.yaml'
    plan_manifest_init P902 plan/P902 main \"\$base\" \"\$base\" plan_branch >/dev/null
    plan_manifest_update P902 \".plan_boundary_manifest.candidate_sha = \\\"\$cand\\\"
      | .plan_boundary_manifest.candidate_frozen_at = \\\"2026-08-06T00:00:00Z\\\"
      | .plan_boundary_manifest.plan_state = \\\"PLAN_MERGING\\\"
      | .plan_boundary_manifest.plan_final_merge = {\\\"result\\\":\\\"merged\\\",\\\"merge_commit\\\":\\\"\$mc\\\",\\\"target_head_before\\\":\\\"\$tb\\\"}\"
    printf '%s' \"\$rev\" > '$TEST_TMPDIR/rev.sha'
  " 3>&-
  [ "$status" -eq 0 ]
  _seed_stale_map "$d" E-902-1_1
  run bash -c "'$PLAN_FSM' plan-rollback P902 --revert-commit \"\$(cat '$TEST_TMPDIR/rev.sha')\" \
    --reason 'test rollback drill' --project-root '$d'" 3>&-
  [ "$status" -eq 0 ]
  [[ "$output" == *"ROLLED BACK: P902"* ]]
  # the boundary sweep removed the gone-state-file entry
  run jq -r 'keys | length' "$d/.aid-o/work/active-runs.json"
  [ "$output" = "0" ]
  local idx="$d/.aid-o/work/active.md"
  [ -f "$idx" ]
  [ "$(head -1 "$idx")" = "$HEADER" ]
  ! grep -q '^- P902' "$idx"
}

# ─── the shared sync helper: prune wiring + best-effort contract ─────────

@test "boundary sync sweeps a stale active-runs entry (Step 4's deferred prune wiring)" {
  local d="$TEST_TMPDIR/root"
  _seed_plan "$d" P901 OPEN
  _seed_stale_map "$d" E-905-1_1   # state file gone entirely
  run bash -c "source '$AI_LIB' && aid_active_boundary_sync '$d' - plan-close" 3>&-
  [ "$status" -eq 0 ]
  run jq -r 'keys | length' "$d/.aid-o/work/active-runs.json"
  [ "$output" = "0" ]
  grep -q 'No active EPIC runs\.' "$d/.aid-o/work/active.md"
  grep -q '^- P901' "$d/.aid-o/work/active.md"
}

@test "render failure (active.md is a directory) warns but the lifecycle command (init) still succeeds" {
  _mk_primary "$TEST_TMPDIR/primary"
  mkdir -p "$TEST_TMPDIR/primary/.aid-o/work/active.md"
  run bash -c "cd '$TEST_TMPDIR/primary' \
    && '$FSM' init E-901-1_1 R-A 1 manual main HEAD '.aid-o/work/evidence/E-901-1_1/R-A/fsm-state.yaml'" 3>&-
  [ "$status" -eq 0 ]
  [[ "$output" == *"WARNING: active-index"* ]]
  [ -f "$TEST_TMPDIR/primary/.aid-o/work/evidence/E-901-1_1/R-A/fsm-state.yaml" ]
  # the run WAS recorded in the map even though the render could not land
  run jq -r 'keys | join(",")' "$TEST_TMPDIR/primary/.aid-o/work/active-runs.json"
  [ "$output" = "E-901-1_1" ]
  [ -d "$TEST_TMPDIR/primary/.aid-o/work/active.md" ]
}

@test "render failure (read-only work dir) warns; the boundary sync itself still returns 0" {
  local d="$TEST_TMPDIR/root"
  _seed_plan "$d" P901 OPEN
  chmod 555 "$d/.aid-o/work"
  run bash -c "source '$AI_LIB' && aid_active_boundary_sync '$d' - plan-rollback" 3>&-
  chmod 755 "$d/.aid-o/work"
  [ "$status" -eq 0 ]
  [[ "$output" == *"WARNING: active-index"* ]]
  [ ! -e "$d/.aid-o/work/active.md" ]
}
