#!/usr/bin/env bats
# test-aid-init-upgrade-test-audit.bats — P069 Step 12.
#
# Proves aid-init-upgrade-test-audit.sh's non-invasive existing-project
# upgrade path:
#   - a fixture execution.yaml with hand-edited, unrelated gates (and, in one
#     case, an already-hand-edited test_audit.scheduler.mode) is upgraded:
#     every byte outside the appended/inserted block is preserved
#   - the diff preview is shown before any write (no --confirm-upgrade)
#   - a missing/wrong --confirm-upgrade hash writes nothing
#   - a correct hash appends exactly the missing piece(s), and never
#     touches an already-present test_audit.scheduler block, hand-edited
#     or not

load test-helpers.bash

setup() {
  TEST_TMPDIR=$(mktemp -d)
  export TEST_TMPDIR
  TEST_PROJECT="$TEST_TMPDIR/project"
  mkdir -p "$TEST_PROJECT/.aid-o/config"
  cd "$TEST_PROJECT"
  AID_PLUGIN_PATH="$(cd "$BATS_TEST_DIRNAME/../../.." && pwd)"
  export AID_PLUGIN_PATH
  UPGRADE="$AID_PLUGIN_PATH/scripts/aid-init-upgrade-test-audit.sh"
  EXEC_YAML="$TEST_PROJECT/.aid-o/config/execution.yaml"
}

teardown() {
  cd /
  [[ -n "${TEST_TMPDIR:-}" && -d "$TEST_TMPDIR" ]] && rm -rf "$TEST_TMPDIR"
}

_write_hand_edited_fixture() {
  cat > "$EXEC_YAML" <<'YAML'
# AUTO-GENERATED by aid-init at 2026-01-01T00:00:00Z
# Detected stacks: typescript
version: "1.0"
generated_by: "aid-init v2.16.0"

gates:
  # === Typescript (auto-detected) ===
  ts_test:
    command: "npm run test:custom -- --shard=1"
    required_when: "*.ts OR *.tsx exists"
    timeout_seconds: 999
  ts_lint:
    command: "npm run lint:strict"
    required_when: "*.ts OR *.tsx exists"

notifications:
  telegram:
    enabled: false
YAML
}

_confirm_hash_from_preview() {
  "$UPGRADE" --project-root "$TEST_PROJECT" | grep '^diff_hash:' | awk '{print $2}'
}

@test "no --confirm-upgrade: preview only, nothing written, exit 0" {
  _write_hand_edited_fixture
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  run "$UPGRADE" --project-root "$TEST_PROJECT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"targeted_tests:"* ]]
  [[ "$output" == *"test_audit:"* ]]
  [[ "$output" == *"diff_hash:"* ]]

  run diff "${EXEC_YAML}.before" "$EXEC_YAML"
  [ "$status" -eq 0 ]
}

@test "wrong/stale --confirm-upgrade hash: refuses, re-displays diff, writes nothing" {
  _write_hand_edited_fixture
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  run "$UPGRADE" --project-root "$TEST_PROJECT" --confirm-upgrade "sha256:0000000000000000000000000000000000000000000000000000000000000000"
  [ "$status" -eq 1 ]
  [[ "$output" == *"diff_hash:"* ]]

  run diff "${EXEC_YAML}.before" "$EXEC_YAML"
  [ "$status" -eq 0 ]
}

@test "correct hash: both pieces missing — both added, hand-edited gates byte-identical, targeted_tests gate a real member of gates:" {
  _write_hand_edited_fixture
  orig_line_count=$(wc -l < "$EXEC_YAML")
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  hash="$(_confirm_hash_from_preview)"
  run "$UPGRADE" --project-root "$TEST_PROJECT" --confirm-upgrade "$hash"
  [ "$status" -eq 0 ]

  # Hand-edited values survived character-for-character.
  run yq '.gates.ts_test.command' "$EXEC_YAML"
  [ "$output" == "npm run test:custom -- --shard=1" ]
  run yq '.gates.ts_test.timeout_seconds' "$EXEC_YAML"
  [ "$output" == "999" ]
  run yq '.gates.ts_lint.command' "$EXEC_YAML"
  [ "$output" == "npm run lint:strict" ]

  # targeted_tests is a REAL member of the existing gates: mapping — not a
  # second, shadowing top-level gates: key that silently drops ts_test/ts_lint.
  run yq '.gates | keys | length' "$EXEC_YAML"
  [ "$output" -eq 3 ]
  run yq '.gates.targeted_tests.command' "$EXEC_YAML"
  [ "$output" == '{plugin_path}/scripts/aid-select-tests.sh --base {base_commit}' ]

  run yq '.test_audit.scheduler.mode' "$EXEC_YAML"
  [ "$output" == "sequential" ]

  # Only ONE top-level `gates:` key exists after the upgrade (never a
  # duplicate that a "last-wins" yq read would silently resolve to).
  run bash -c "grep -c '^gates:' '$EXEC_YAML'"
  [ "$output" -eq 1 ]

  # File is still valid, single-document YAML.
  run bash -c "yq -e '.' '$EXEC_YAML' > /dev/null"
  [ "$status" -eq 0 ]
}

@test "already-hand-edited test_audit.scheduler.mode (observe_parallel): never overwritten, only the missing targeted_tests gate is added" {
  _write_hand_edited_fixture
  cat >> "$EXEC_YAML" <<'YAML'

test_audit:
  scheduler:
    mode: observe_parallel
    resource_locks:
      shared_db: ["suite-a", "suite-b"]
YAML
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  hash="$(_confirm_hash_from_preview)"
  # Preview must show ONLY the missing gate piece — never the already-present
  # test_audit block.
  preview="$("$UPGRADE" --project-root "$TEST_PROJECT")"
  [[ "$preview" == *"targeted_tests:"* ]]
  [[ "$preview" != *"mode: sequential"* ]]

  run "$UPGRADE" --project-root "$TEST_PROJECT" --confirm-upgrade "$hash"
  [ "$status" -eq 0 ]

  # The hand-edited scheduler block is untouched, byte-for-byte.
  run yq '.test_audit.scheduler.mode' "$EXEC_YAML"
  [ "$output" == "observe_parallel" ]
  run yq '.test_audit.scheduler.resource_locks.shared_db | join(",")' "$EXEC_YAML"
  [ "$output" == "suite-a,suite-b" ]

  # targeted_tests gate was still added.
  run yq '.gates.targeted_tests.command' "$EXEC_YAML"
  [ "$output" == '{plugin_path}/scripts/aid-select-tests.sh --base {base_commit}' ]
}

@test "already-hand-edited targeted_tests gate command: never overwritten, only the missing test_audit block is added" {
  # A fixture with a hand-edited targeted_tests gate already a genuine
  # member of the gates: mapping (custom flags), built directly rather than
  # via _write_hand_edited_fixture + post-hoc insertion.
  cat > "$EXEC_YAML" <<'YAML'
# AUTO-GENERATED by aid-init at 2026-01-01T00:00:00Z
version: "1.0"

gates:
  targeted_tests:
    command: "custom-selector --flag"
    required: true
  ts_test:
    command: "npm run test:custom -- --shard=1"

notifications:
  telegram:
    enabled: false
YAML
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  hash="$(_confirm_hash_from_preview)"
  preview="$("$UPGRADE" --project-root "$TEST_PROJECT")"
  [[ "$preview" == *"test_audit:"* ]]
  [[ "$preview" != *"custom-selector"* ]]
  [[ "$preview" != *'{plugin_path}/scripts/aid-select-tests.sh'* ]]

  run "$UPGRADE" --project-root "$TEST_PROJECT" --confirm-upgrade "$hash"
  [ "$status" -eq 0 ]

  run yq '.gates.targeted_tests.command' "$EXEC_YAML"
  [ "$output" == "custom-selector --flag" ]
  run yq '.test_audit.scheduler.mode' "$EXEC_YAML"
  [ "$output" == "sequential" ]
}

@test "both pieces already present: no-op, nothing written, no diff shown" {
  _write_hand_edited_fixture
  hash1="$(_confirm_hash_from_preview)"
  "$UPGRADE" --project-root "$TEST_PROJECT" --confirm-upgrade "$hash1" >/dev/null

  cp "$EXEC_YAML" "${EXEC_YAML}.before"
  run "$UPGRADE" --project-root "$TEST_PROJECT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"nothing to upgrade"* ]]

  run diff "${EXEC_YAML}.before" "$EXEC_YAML"
  [ "$status" -eq 0 ]
}

@test "--project-root is required and must exist; missing execution.yaml fails loud" {
  run "$UPGRADE"
  [ "$status" -eq 2 ]

  run "$UPGRADE" --project-root "$TEST_TMPDIR/does-not-exist"
  [ "$status" -eq 3 ]

  mkdir -p "$TEST_TMPDIR/empty-project"
  run "$UPGRADE" --project-root "$TEST_TMPDIR/empty-project"
  [ "$status" -eq 3 ]
  [[ "$output" == *"run /aid-init first"* ]]
}

# ─── Codex review (P069 Step 12): 3 real findings, regression-tested ────────

@test "Codex HIGH: a pre-existing duplicate top-level 'gates:' key is refused outright, never silently inserted into the wrong (shadowed) mapping" {
  cat > "$EXEC_YAML" <<'YAML'
version: "1.0"
gates:
  old_first:
    command: "true"
gates:
  old_last:
    command: "true"
YAML
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  run "$UPGRADE" --project-root "$TEST_PROJECT"
  [ "$status" -eq 1 ]
  [[ "$output" == *"duplicate-key hazard"* ]]

  run diff "${EXEC_YAML}.before" "$EXEC_YAML"
  [ "$status" -eq 0 ]
}

@test "Codex HIGH: a pre-existing duplicate top-level 'test_audit:' key is refused outright" {
  cat > "$EXEC_YAML" <<'YAML'
version: "1.0"
gates:
  alpha:
    command: "true"
test_audit:
  note: first
test_audit:
  note: last
YAML
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  run "$UPGRADE" --project-root "$TEST_PROJECT"
  [ "$status" -eq 1 ]
  [[ "$output" == *"duplicate-key hazard"* ]]

  run diff "${EXEC_YAML}.before" "$EXEC_YAML"
  [ "$status" -eq 0 ]
}

@test "Codex HIGH: an explicit 'targeted_tests: null' placeholder counts as present (key exists) — never shadowed by a second inserted gate" {
  cat > "$EXEC_YAML" <<'YAML'
version: "1.0"
gates:
  targeted_tests: null
  alpha:
    command: "true"
test_audit:
  note: keep-me
  scheduler: null
YAML
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  # Both pieces are technically KEY-present (even though null) — nothing to
  # upgrade, and the file is untouched.
  run "$UPGRADE" --project-root "$TEST_PROJECT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"nothing to upgrade"* ]]

  run diff "${EXEC_YAML}.before" "$EXEC_YAML"
  [ "$status" -eq 0 ]

  # Sanity: only ONE targeted_tests key and no duplicate gates:/test_audit:
  # lines were ever introduced.
  run bash -c "yq '.gates | keys | map(select(. == \"targeted_tests\")) | length' '$EXEC_YAML'"
  [ "$output" -eq 1 ]
}

@test "Codex HIGH: test_audit: exists with an unrelated sibling field but no scheduler — scheduler is merged in, sibling field survives, never shadowed by a duplicate top-level test_audit: key" {
  cat > "$EXEC_YAML" <<'YAML'
version: "1.0"
gates:
  alpha:
    command: "true"
test_audit:
  note: keep-me
YAML
  cp "$EXEC_YAML" "${EXEC_YAML}.before"

  hash="$(_confirm_hash_from_preview)"
  preview="$("$UPGRADE" --project-root "$TEST_PROJECT")"
  [[ "$preview" == *"scheduler"* ]]
  [[ "$preview" == *"existing top-level test_audit: mapping"* ]]

  run "$UPGRADE" --project-root "$TEST_PROJECT" --confirm-upgrade "$hash"
  [ "$status" -eq 0 ]

  # Sibling field survived — never shadowed by a duplicate top-level key.
  run yq '.test_audit.note' "$EXEC_YAML"
  [ "$output" == "keep-me" ]
  run yq '.test_audit.scheduler.mode' "$EXEC_YAML"
  [ "$output" == "sequential" ]
  run bash -c "grep -c '^test_audit:' '$EXEC_YAML'"
  [ "$output" -eq 1 ]
}

@test "Codex MEDIUM: the confirm hash is bound to the file's current content — a stale hash from a DIFFERENT (or since-edited) file is rejected" {
  _write_hand_edited_fixture
  hash_a="$(_confirm_hash_from_preview)"

  # A second, independent project missing the exact same subset of pieces
  # gets a DIFFERENT hash, because the hash is bound to file content too.
  local proj_b="$TEST_TMPDIR/project-b"
  mkdir -p "$proj_b/.aid-o/config"
  local exec_yaml_b="$proj_b/.aid-o/config/execution.yaml"
  cat > "$exec_yaml_b" <<'YAML'
version: "1.0"
gates:
  totally-different-gate-name:
    command: "echo different"
YAML
  hash_b="$("$UPGRADE" --project-root "$proj_b" | grep '^diff_hash:' | awk '{print $2}')"
  [ "$hash_a" != "$hash_b" ]

  # project A's hash is refused against project B.
  run "$UPGRADE" --project-root "$proj_b" --confirm-upgrade "$hash_a"
  [ "$status" -eq 1 ]

  # An unrelated edit to project A's file BETWEEN preview and confirm
  # (touching a hand-edited gate's command, not the two presence booleans)
  # invalidates the previously-shown hash.
  sed -i 's/--shard=1/--shard=2/' "$EXEC_YAML"
  run "$UPGRADE" --project-root "$TEST_PROJECT" --confirm-upgrade "$hash_a"
  [ "$status" -eq 1 ]
}
