import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        title: 'Architecture',
        description: 'How AID Orchestrator is designed and how its components work together.',
        slug: '/architecture',
      },
      items: [
        'architecture/overview',
        'architecture/orchestration-flow',
        'architecture/quality-gates',
        'architecture/memory-system',
        'architecture/first-aid-mode',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Learn how to install and configure AID Orchestrator.',
        slug: '/getting-started',
      },
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Commands',
      link: {
        type: 'generated-index',
        title: 'Commands',
        description: 'All AID Orchestrator slash commands.',
        slug: '/commands',
      },
      items: [
        'commands/aid-analytics',
        'commands/aid-audit',
        'commands/aid-brainstorm',
        'commands/aid-epic-queue',
        'commands/aid-epic-status',
        'commands/aid-first-aid',
        'commands/aid-help',
        'commands/aid-init',
        'commands/aid-plan-epic',
        'commands/aid-research',
        'commands/aid-run-epic',
        'commands/aid-setup',
        'commands/aid-stop',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      link: {
        type: 'generated-index',
        title: 'Agents',
        description: 'Specialized role-based agents dispatched during EPIC execution.',
        slug: '/agents',
      },
      items: [
        'agents/overview',
        'agents/architect',
        'agents/auditor',
        'agents/backend',
        'agents/code-reviewer',
        'agents/curator',
        'agents/docs-reviewer',
        'agents/docs-writer',
        'agents/domain',
        'agents/frontend',
        'agents/gate-fixer',
        'agents/lessons-extractor',
        'agents/observability',
        'agents/project-scanner',
        'agents/qa',
        'agents/quality-gates-runner',
        'agents/release',
        'agents/run-validator',
        'agents/security',
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      link: {
        type: 'generated-index',
        title: 'Skills',
        description: 'Reusable orchestration skills that power AID agents.',
        slug: '/skills',
      },
      items: [
        'skills/overview',
        'skills/agent-core',
        'skills/analysis-merge',
        'skills/analytics',
        'skills/auto-done-state',
        'skills/auto-escalation',
        'skills/brainstorming',
        'skills/cost-optimization',
        'skills/epic-orchestration',
        'skills/epic-queue',
        'skills/gates-engine',
        'skills/improvement-proposals',
        'skills/knowledge-acquisition',
        'skills/memory-mcp',
        'skills/parallel-dispatch',
        'skills/permission-sandwich',
        'skills/planner',
        'skills/quality-gates',
        'skills/retry-engine',
        'skills/run-management',
        'skills/slack-mcp',
        'skills/workflow-intelligence',
      ],
    },
  ],
};

export default sidebars;
